### ISSUE TITLE
TypeError: init() missing 1 required positional argument: 'argv' on Linux Mint 19

### ISSUE THREAD

**Issue by di8905** [dlenski/gp-saml-gui#39]
When i trying to connect to vpn "gp-saml-gui --gateway --clientos=Linux mysite" i get an error: 
```Got SAML REDIRECT, opening browser...
Traceback (most recent call last):
  File "/home/di/.local/bin/gp-saml-gui", line 33, in <module>
    sys.exit(load_entry_point('gp-saml-gui==0.1', 'console_scripts', 'gp-saml-gui')())
  File "/home/di/.local/lib/python3.5/site-packages/gp_saml_gui.py", line 263, in main
    slv = SAMLLoginView(uri, html, verbose=args.verbose, cookies=args.cookies, verify=args.verify)
  File "/home/di/.local/lib/python3.5/site-packages/gp_saml_gui.py", line 36, in __init__
    Gtk.init()
TypeError: init() missing 1 required positional argument: 'argv'
```

My system is Linux Mint 19.1.
I've tried it on clean fresh install of Linux Mint 20.1 and it works fine. Also I've tried to update python to 3.9 but without luck.

**Comment by UlrichEckhardt** [comment]
Works here, without any arguments to `Gtk.init()`. I'm using Python 3.9 here though. I could imagine that the used libraries make a difference though, what are the versions there?

**Comment by DimitriPapadopoulos** [comment]
The current documentation does specify a mandatory **argv** argument for `Gtk.init()`:
https://lazka.github.io/pgi-docs/#Gtk-3.0/functions.html#Gtk.init

> **argv** ([[str](http://docs.python.org/3/library/stdtypes.html#str)] or [None](http://docs.python.org/3/library/constants.html#None))

**Comment by DimitriPapadopoulos** [comment]
In GTK 4, `gtk_init()` does not need an argument:

https://gitlab.gnome.org/GNOME/gtk/-/blob/gtk-4-6/gtk/gtkmain.c#L645
```c
/**
 * gtk_init:
 *
 * Call this function before using any other GTK functions in your GUI
 * applications.  It will initialize everything needed to operate the
 * toolkit.
 *
 * If you are using `GtkApplication`, you don't have to call gtk_init()
 * or gtk_init_check(); the `GApplication::startup` handler
 * does it for you.
 *
 * This function will terminate your program if it was unable to
 * initialize the windowing system for some reason. If you want
 * your program to fall back to a textual interface you want to
 * call gtk_init_check() instead.
 *
 * GTK calls `signal (SIGPIPE, SIG_IGN)`
 * during initialization, to ignore SIGPIPE signals, since these are
 * almost never wanted in graphical applications. If you do need to
 * handle SIGPIPE for some reason, reset the handler after gtk_init(),
 * but notice that other libraries (e.g. libdbus or gvfs) might do
 * similar things.
 */
void
gtk_init (void)
{
```
but it does in GTK 3:

https://gitlab.gnome.org/GNOME/gtk/-/blob/gtk-3-24/gtk/gtkmain.c#L1165
```c
/**
 * gtk_init:
 * @argc: (inout): Address of the `argc` parameter of
 *     your main() function (or 0 if @argv is %NULL). This will be changed if 
 *     any arguments were handled.
 * @argv: (array length=argc) (inout) (allow-none): Address of the
 *     `argv` parameter of main(), or %NULL. Any options
 *     understood by GTK+ are stripped before return.
 *
 * Call this function before using any other GTK+ functions in your GUI
 * applications.  It will initialize everything needed to operate the
 * toolkit and parses some standard command line options.
 *
 * Although you are expected to pass the @argc, @argv parameters from main() to 
 * this function, it is possible to pass %NULL if @argv is not available or 
 * commandline handling is not required.
 *
 * @argc and @argv are adjusted accordingly so your own code will
 * never see those standard arguments.
 *
 * Note that there are some alternative ways to initialize GTK+:
 * if you are calling gtk_parse_args(), gtk_init_check(),
 * gtk_init_with_args() or g_option_context_parse() with
 * the option group returned by gtk_get_option_group(),
 * you don’t have to call gtk_init().
 *
 * And if you are using #GtkApplication, you don't have to call any of the
 * initialization functions either; the #GtkApplication::startup handler
 * does it for you.
 *
 * This function will terminate your program if it was unable to
 * initialize the windowing system for some reason. If you want
 * your program to fall back to a textual interface you want to
 * call gtk_init_check() instead.
 *
 * Since 2.18, GTK+ calls `signal (SIGPIPE, SIG_IGN)`
 * during initialization, to ignore SIGPIPE signals, since these are
 * almost never wanted in graphical applications. If you do need to
 * handle SIGPIPE for some reason, reset the handler after gtk_init(),
 * but notice that other libraries (e.g. libdbus or gvfs) might do
 * similar things.
 */
void
gtk_init (int *argc, char ***argv)
{
```

**Comment by DimitriPapadopoulos** [comment]
@di8905 and @UlrichEckhardt Could you perhaps check it works for both of you after changing `Gtk.init()` to `Gtk.init(None)`?
