### ISSUE TITLE
README.md should avoid non-ascii characters

### ISSUE THREAD

**Issue by seriv** [dlenski/gp-saml-gui#63]
I am getting on RH7:
```
pip3 install https://github.com/dlenski/gp-saml-gui/archive/master.zip
Collecting https://github.com/dlenski/gp-saml-gui/archive/master.zip
  Using cached https://github.com/dlenski/gp-saml-gui/archive/master.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-jbakt529-build/setup.py", line 18, in <module>
        long_description=open("README.md").read(),
      File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4972: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-jbakt529-build/
```
As I understand it was caused by a funny character on line 126 of README.md.

**Comment by dlenski** [comment]
Rather than remove non-ASCII characters, we should just modify `setup.py` to correctly recognize the encoding of `README.md` (`utf-8`).

I hadn't seen this before. RH7 is old and I guess it doesn't have `utf-8` as its default encoding.
