### ISSUE TITLE
Not working w/ Fedora 37

### ISSUE THREAD

**Issue by mauriziomarini** [dlenski/gp-saml-gui#68]
just upgraded my Fedora 36 to Fedora 37 et voila'

`
gp-saml-gui -S --gateway --no-verify --clientos=Linux xxx.xxxxxx.it
Traceback (most recent call last):
  File "/home/maurizio/.local/bin/gp-saml-gui", line 33, in <module>
    sys.exit(load_entry_point('gp-saml-gui==0.1', 'console_scripts', 'gp-saml-gui')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maurizio/.local/bin/gp-saml-gui", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/metadata/__init__.py", line 964, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/metadata/__init__.py", line 561, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for gp-saml-gui

`

**Comment by mauriziomarini** [comment]
it necessary to reinstall package
pip3 install https://github.com/dlenski/gp-saml-gui/archive/master.zip
