### ISSUE TITLE
fgets (stdin): Inappropriate ioctl for device

### ISSUE THREAD

**Issue by piakbt** [dlenski/gp-saml-gui#88]
Hello!

Could you please help me with this?
I'm getting error "fgets (stdin): Inappropriate ioctl for device".

The steps are:
1.
```
$ eval $( gp-saml-gui --portal --clientos=Mac aa1.vpn.mycompany.com -- --csd-wrapper=/usr/libexec/openconnect/hipreport.sh )

Looking for SAML auth tags in response to https://aa1.vpn.mycompany.com/global-protect/prelogin.esp...
Got SAML POST, opening browser...
Traceback (most recent call last):
  File "/home/paul/.local/lib/python3.12/site-packages/gp_saml_gui.py", line 127, in on_load_changed
    ct = h.get_content_type()
         ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_content_type'
[PAGE   ] Finished loading page https://mycompany.okta.com/app/panw_globalprotect/exk3s5nzpziXEw98A297/sso/saml
[PAGE   ] Finished loading page https://mycompany.okta.com/login/sessionCookieRedirect
[PAGE   ] Finished loading page https://aa1.vpn.mycompany.com//SAML20/SP/ACS
[SAML   ] Got SAML result headers: {'saml-username': 'mycompany\\mylogin', 'prelogin-cookie': '<token>', 'saml-slo': 'no', 'saml-auth-status': '1'}
[SAML   ] Got all required SAML headers, done.
IMPORTANT: We started with SAML auth to the portal interface, but received a cookie that's often associated with the gateway interface. You should probably try both.

SAML response converted to OpenConnect command line invocation:

    echo <token> |
        sudo openconnect --protocol=gp '--useragent=PAN GlobalProtect' '--user=mycompany\mylogin' --os=mac-intel --usergroup=portal:prelogin-cookie --passwd-on-stdin aa1.vpn.mycompany.com --csd-wrapper=/usr/libexec/openconnect/hipreport.sh

SAML response converted to test-globalprotect-login.py invocation:

    test-globalprotect-login.py --user='mycompany\mylogin' --clientos=Mac -p '' \
         https://aa1.vpn.mycompany.com/global-protect/getconfig.esp prelogin-cookie=<token>
```
2.
```
$ echo <token> |
        sudo openconnect --protocol=gp '--useragent=PAN GlobalProtect' '--user=mycompany\mylogin' --os=mac-intel --usergroup=portal:prelogin-cookie --passwd-on-stdin ab1.vpn.mycompany.com --csd-wrapper=/usr/libexec/openconnect/hipreport.sh 

POST https://aa1.vpn.mycompany.com/global-protect/prelogin.esp?tmp=tmp&clientVer=4100&clientos=Mac
Connected to 11.111.111.11:443
SSL negotiation with aa1.vpn.mycompany.com
Connected to HTTPS on aa1.vpn.mycompany.com with ciphersuite (TLS1.2)-(ECDHE-SECP256R1)-(RSA-SHA256)-(AES-256-GCM)
Enter login credentials
POST https://aa1.vpn.mycompany.com/global-protect/getconfig.esp
Portal reports GlobalProtect version 6.1.1-5; we will report the same client version.
Portal set HIP report interval to 60 minutes).
1 gateway servers available:
  bb1.vpn.mycompany.com (bb1.vpn.mycompany.com)
Please select GlobalProtect gateway.
GATEWAY: [bb1.vpn.mycompany.com]:bb1.vpn.mycompany.com
POST https://bb1.vpn.mycompany.com/ssl-vpn/prelogin.esp?tmp=tmp&clientVer=4100&clientos=Mac
Connected to 2.22.22.222:443
SSL negotiation with bb1.vpn.mycompany.com
Connected to HTTPS on bb1.vpn.mycompany.com with ciphersuite (TLS1.2)-(ECDHE-SECP256R1)-(RSA-SHA256)-(AES-256-GCM)
Enter login credentials
prelogin-cookie: 
fgets (stdin): Inappropriate ioctl for device
```

**Comment by piakbt** [comment]
This line made me try to connect to the gateway directly:
`IMPORTANT: We started with SAML auth to the portal interface, but received a cookie that's often associated with the gateway interface. You should probably try both.`

I do this and I have partial access. One resource is available, others not - so strange.

```
eval $( gp-saml-gui -S --gateway --clientos=Mac bb1.vpn.mycompany.com -- --csd-wrapper=/usr/libexec/openconnect/hipreport.sh )

Looking for SAML auth tags in response to https://bb1.vpn.mycompany.com/ssl-vpn/prelogin.esp...
Got SAML POST, opening browser...
Traceback (most recent call last):
  File "/home/paul/.local/lib/python3.12/site-packages/gp_saml_gui.py", line 127, in on_load_changed
    ct = h.get_content_type()
         ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_content_type'
[PAGE   ] Finished loading page https://mycompany.okta.com/app/panw_globalprotect/exkd9gesu3A19vjY6297/sso/saml
[PAGE   ] Finished loading page https://mycompany.okta.com/login/sessionCookieRedirect
[PAGE   ] Finished loading page https://bb1.vpn.mycompany.com/SAML20/SP/ACS
[SAML   ] Got SAML result tags: {'saml-auth-status': '1', 'prelogin-cookie': '<token>', 'saml-username': 'mylogin@mycompany.com', 'saml-slo': 'no', 'saml-SessionNotOnOrAfter': None}
[SAML   ] Got all required SAML headers, done.

SAML response converted to OpenConnect command line invocation:

    echo <token> |
        sudo openconnect --protocol=gp '--useragent=PAN GlobalProtect' --user=mylogin@mycompany.com --os=mac-intel --usergroup=gateway:prelogin-cookie --passwd-on-stdin bb1.vpn.mycompany.com --csd-wrapper=/usr/libexec/openconnect/hipreport.sh

SAML response converted to test-globalprotect-login.py invocation:

    test-globalprotect-login.py --user=mylogin@mycompany.com --clientos=Mac -p '' \
         https://bb1.vpn.mycompany.com/ssl-vpn/login.esp prelogin-cookie=<token>

Launching OpenConnect with sudo, equivalent to:
    echo <token> |
        sudo openconnect --protocol=gp '--useragent=PAN GlobalProtect' --user=mylogin@mycompany.com --os=mac-intel --usergroup=gateway:prelogin-cookie --passwd-on-stdin bb1.vpn.mycompany.com --csd-wrapper=/usr/libexec/openconnect/hipreport.sh
[sudo] password for paul: 
Enter login credentials
GlobalProtect login returned unexpected argument value arg[21]=AWS-BB1
Please report 1 unexpected values above (of which 0 fatal) to <openconnect-devel@lists.infradead.org>
Did not receive ESP keys and matching gateway in GlobalProtect config; tunnel will be TLS only.
No MTU received. Calculated 1455 for SSL tunnel. No ESP keys received
Set up UDP failed; using SSL instead
```

I am aware of this issue: https://github.com/dlenski/gp-saml-gui/issues/17
but I'm already using HIP report script.

Could you consider any solution please?

**Comment by marvinhrivera** [comment]
> Hello!
> 
> Could you please help me with this? I'm getting error "fgets (stdin): Inappropriate ioctl for device".
> 
> The steps are: 1.
> 
> ```
> $ eval $( gp-saml-gui --portal --clientos=Mac aa1.vpn.mycompany.com -- --csd-wrapper=/usr/libexec/openconnect/hipreport.sh )
> 
> Looking for SAML auth tags in response to https://aa1.vpn.mycompany.com/global-protect/prelogin.esp...
> Got SAML POST, opening browser...
> Traceback (most recent call last):
>   File "/home/paul/.local/lib/python3.12/site-packages/gp_saml_gui.py", line 127, in on_load_changed
>     ct = h.get_content_type()
>          ^^^^^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'get_content_type'
> [PAGE   ] Finished loading page https://mycompany.okta.com/app/panw_globalprotect/exk3s5nzpziXEw98A297/sso/saml
> [PAGE   ] Finished loading page https://mycompany.okta.com/login/sessionCookieRedirect
> [PAGE   ] Finished loading page https://aa1.vpn.mycompany.com//SAML20/SP/ACS
> [SAML   ] Got SAML result headers: {'saml-username': 'mycompany\\mylogin', 'prelogin-cookie': '<token>', 'saml-slo': 'no', 'saml-auth-status': '1'}
> [SAML   ] Got all required SAML headers, done.
> IMPORTANT: We started with SAML auth to the portal interface, but received a cookie that's often associated with the gateway interface. You should probably try both.
> 
> SAML response converted to OpenConnect command line invocation:
> 
>     echo <token> |
>         sudo openconnect --protocol=gp '--useragent=PAN GlobalProtect' '--user=mycompany\mylogin' --os=mac-intel --usergroup=portal:prelogin-cookie --passwd-on-stdin aa1.vpn.mycompany.com --csd-wrapper=/usr/libexec/openconnect/hipreport.sh
> 
> SAML response converted to test-globalprotect-login.py invocation:
> 
>     test-globalprotect-login.py --user='mycompany\mylogin' --clientos=Mac -p '' \
>          https://aa1.vpn.mycompany.com/global-protect/getconfig.esp prelogin-cookie=<token>
> ```
> 
> 
> ```
> $ echo <token> |
>         sudo openconnect --protocol=gp '--useragent=PAN GlobalProtect' '--user=mycompany\mylogin' --os=mac-intel --usergroup=portal:prelogin-cookie --passwd-on-stdin ab1.vpn.mycompany.com --csd-wrapper=/usr/libexec/openconnect/hipreport.sh 
> 
> POST https://aa1.vpn.mycompany.com/global-protect/prelogin.esp?tmp=tmp&clientVer=4100&clientos=Mac
> Connected to 11.111.111.11:443
> SSL negotiation with aa1.vpn.mycompany.com
> Connected to HTTPS on aa1.vpn.mycompany.com with ciphersuite (TLS1.2)-(ECDHE-SECP256R1)-(RSA-SHA256)-(AES-256-GCM)
> Enter login credentials
> POST https://aa1.vpn.mycompany.com/global-protect/getconfig.esp
> Portal reports GlobalProtect version 6.1.1-5; we will report the same client version.
> Portal set HIP report interval to 60 minutes).
> 1 gateway servers available:
>   bb1.vpn.mycompany.com (bb1.vpn.mycompany.com)
> Please select GlobalProtect gateway.
> GATEWAY: [bb1.vpn.mycompany.com]:bb1.vpn.mycompany.com
> POST https://bb1.vpn.mycompany.com/ssl-vpn/prelogin.esp?tmp=tmp&clientVer=4100&clientos=Mac
> Connected to 2.22.22.222:443
> SSL negotiation with bb1.vpn.mycompany.com
> Connected to HTTPS on bb1.vpn.mycompany.com with ciphersuite (TLS1.2)-(ECDHE-SECP256R1)-(RSA-SHA256)-(AES-256-GCM)
> Enter login credentials
> prelogin-cookie: 
> fgets (stdin): Inappropriate ioctl for device
> ```

I'm having the same issue since a couple of days ago, the same error message at the end "fgets (stdin): Inappropriate ioctl for device"
However I played a bit with the parameters and I found out that on Step 2 if I remove --passwd-on-stdin parameter then it will actually go through and authenticate, could you test if this works for you as well?

**Comment by piakbt** [comment]
Hey @marvinhrivera ! Thanks for the reply.
Ah, I get the same error without '--passwd-on-stdin' parameter.

**Comment by driehuis** [comment]
I see the same symptoms when I leave out the `--gateway` parameter. The message `IMPORTANT: We started with SAML auth to the portal interface, but received a cookie that's often associated with the gateway interface.` seems to be the clue.

You may want to try replacing --portal with --gateway.

**Comment by Kabouik** [comment]
I can confirm I needed to use the `--gateway` flag too when invoking the `gp-saml-gui` command.

For reference, my VPN system normally gives me a choice for two distinct server locations when I just connect to it using `openconnect`, and this is not the case here, but it did connect at least. If I don't use `--gateway`, then I can see the two servers being listed briefly but no connection is made to any of them, and upon retrying the same command generated by `gp-saml-gui`, I get the `Inappropriate ioctl for device` error too.

This is all with a TOTP code from a mobile 2FA application. I have had no luck when trying to use a hardware key. All I get is "Webauthn required" and a "Retry" button in the GUI, which will say that my browser (the GUI) doesn't support Webauthn when I press it. Maybe the `-x` flag would help in that case.

**Comment by smetheny-arch** [comment]
This comment was AI generated after I had it fix my issues.  I don't code at this level. But I thought it would be helpful to share what was learned. Please treat accordingly.
Confirming this on current `master`, with what I think is the root cause.

### Environment

- gp-saml-gui at commit `21cce40334791a533c7a263fe367f0ddc072d8fb` (2024-11-19)
- OpenConnect 9.12 (GnuTLS 3.8.13)
- Fedora 44, Python 3.14.6, webkit2gtk4.1 2.52.5, PyGObject 3.56.3
- Portal is PAN-OS with SAML POST auth to a Duo SSO IdP
  (`<prelogin-response>` advertises `saml-auth-method=POST` and
  `saml-default-browser=yes`)

### What happens

Running against the **portal** interface:

```
$ gp-saml-gui -S vpn.example.edu
```

SAML completes correctly and the required headers come back:

```
[SAML   ] Got SAML result headers: {'prelogin-cookie': '<REDACTED>',
          'saml-auth-status': '1', 'saml-slo': 'no',
          'saml-username': 'EXAMPLE\\user'}
[SAML   ] Got all required SAML headers, done.
IMPORTANT: We started with SAML auth to the portal interface, but received a
cookie that's often associated with the gateway interface. You should probably
try both.
```

gp-saml-gui then execs openconnect anyway, using `--usergroup=portal:prelogin-cookie`.
The portal stage succeeds, openconnect enumerates gateways, and then asks for a
*second* cookie for the gateway stage — at which point it dies:

```
POST https://vpn.example.edu/global-protect/getconfig.esp
Portal reports GlobalProtect version 6.3.0-33; we will report the same client version.
1 gateway servers available:
  Example Gateway (vpn.example.edu)
Please select GlobalProtect gateway.
GATEWAY: [Example Gateway]:Example Gateway
POST https://vpn.example.edu/ssl-vpn/prelogin.esp?tmp=tmp&clientVer=4100&clientos=Linux
Log in using your organization credentials
prelogin-cookie:
fgets (stdin): Inappropriate ioctl for device
```

### Root cause

Two things combine here, and I think the first is the actual bug:

1. **The interface mismatch is detected and then ignored.** At
   `gp_saml_gui.py:454-457`, when the cookie's apparent interface (`ifh`) differs
   from the requested one (`args.interface`), the tool prints a warning and
   proceeds regardless:

   ```python
   if ifh != args.interface and not args.uri:
       print('''IMPORTANT: We started with SAML auth to the {} interface, but received a cookie '''
             '''that's often associated with the {} interface. You should probably try both.\n'''.format(args.interface, ifh),
             file=stderr)
   ```

   The `--usergroup` value is built from `args.interface` at line 418
   (`urlpath = args.interface + ":" + cn`), so the exec uses the interface the
   tool has just concluded is probably wrong.

2. **The `fgets` error is a symptom, not the fault.** Because the cookie is
   delivered with `--passwd-on-stdin`, openconnect's stdin is a pipe that is
   exhausted after the first read. When the gateway stage prompts for its own
   `prelogin-cookie`, there is no terminal to read from, so it fails with
   `fgets (stdin): Inappropriate ioctl for device` rather than anything that
   points at the real problem.

So the user sees a misleading I/O error, when what actually happened is that
gp-saml-gui knowingly used the wrong interface.

### Workaround

Authenticating against the gateway interface directly works, first try:

```
$ gp-saml-gui -S -g vpn.example.edu
```

With `-g`, both the SAML endpoint (line 336) and the `--usergroup` value become
gateway-based, openconnect skips the portal handoff entirely, and the tunnel
comes up with no further prompts.

### Suggested fixes

Any of these would have saved a lot of guesswork, roughly in order of preference:

1. When `ifh != args.interface`, re-run the SAML exchange against the detected
   interface automatically (perhaps behind a flag to opt out).
2. Refuse to exec on mismatch, and print the exact corrected command line
   (`... -g ...`) instead of "you should probably try both".
3. Keep the current behaviour but make the failure legible — e.g. when `--exec`
   is used with `--passwd-on-stdin`, warn that openconnect will not be able to
   prompt for any subsequent credential.
